spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/note_db
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        spring:
          jpa:
            hibernate:
              ddl-auto: update
          datasource:
            url: jdbc:mysql://localhost:5432/note_db
            username: postgres
            password: qwerty